/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("buildlogic.java-conventions")
}

dependencies {
    api(project(":commonmark"))
    api(libs.org.nibor.autolink.autolink)
    testImplementation(project(":commonmark-test-util"))
}

description = "commonmark-java extension for autolinking"
