/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("buildlogic.java-conventions")
}

dependencies {
    api(project(":commonmark"))
    api(project(":commonmark-ext-autolink"))
    api(project(":commonmark-ext-ins"))
    api(project(":commonmark-ext-gfm-strikethrough"))
    api(project(":commonmark-ext-gfm-tables"))
    api(project(":commonmark-ext-image-attributes"))
    api(project(":commonmark-ext-task-list-items"))
    api(project(":commonmark-ext-yaml-front-matter"))
    testImplementation(libs.org.pegdown.pegdown)
    testImplementation(project(":commonmark-test-util"))
    testImplementation(libs.org.openjdk.jmh.jmh.core)
    testImplementation(libs.org.openjdk.jmh.jmh.generator.annprocess)
}

description = "commonmark-java integration tests"
