/*
 * This file was generated by the Gradle 'init' task.
 */

rootProject.name = "commonmark-parent"
include(":commonmark-ext-ins")
include(":commonmark-ext-gfm-strikethrough")
include(":commonmark-ext-yaml-front-matter")
include(":commonmark")
include(":commonmark-integration-test")
include(":commonmark-ext-footnotes")
include(":commonmark-ext-heading-anchor")
include(":commonmark-ext-task-list-items")
include(":commonmark-ext-gfm-tables")
include(":commonmark-ext-image-attributes")
include(":commonmark-ext-autolink")
include(":commonmark-test-util")
